# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/tools/cutImg/z123
Accept: application/json

###

GET http://127.0.0.1:8000/tools/cutImg/z123
Accept: application/json

### 裁剪指定路径下所有图片 去除小红书水印
GET http://127.0.0.1:8000/tools/cutImg//Users/griffith/Downloads/cut/
Accept: application/json

### 请求计算收益率
GET http://127.0.0.1:8000/tools/calculateOptionYield
Accept: application/json

### 根据链接处理笔记数据
GET http://127.0.0.1:8000/tools/getImgViaUrl?url=https://www.xiaohongshu.com/explore/688d6a8a00000000250232ad?xsec_token=ABVN7E_Gyhk04Nbwv0c7ZyxTMoOr5Sn1SEVRzIYJnYd00=&xsec_source=pc_collect
Accept: application/json